### ISSUE TITLE
Deprecated doc ?

### ISSUE THREAD

**Issue by riderx** [capawesome-team/capacitor-firebase#574]
I was installing the analytic SDK and found this line:
https://github.com/capawesome-team/capacitor-firebase/blame/4d2111872d1b08e12d7a111d0516912f5f957238/packages/analytics/README.md#L30C3-L30C6
When I install the plugin I see already this link by the plugin, so probably this is outdated.

**Comment by robingenz** [comment]
No, this line is still necessary, because no deps are added by default, see https://github.com/capawesome-team/capacitor-firebase/blob/4d2111872d1b08e12d7a111d0516912f5f957238/packages/analytics/CapacitorFirebaseAnalytics.podspec#L18

Here you can find an example: https://github.com/robingenz/capacitor-firebase-plugin-demo/blob/main/ios/App/Podfile

I will close this for now. Let me know if you have any more questions.
