### ISSUE TITLE
bug: no accessToken 

### ISSUE THREAD

**Issue by lucasschulte** [capawesome-team/capacitor-firebase#65]
**Plugin(s):**
authentication 0.2.1

**Platform(s):**
Android/iOS

**Current behavior:**
Can not get the accessToken with Google Login on Android and
can not get the accessToken with Microsoft Login on iOS.

Did not test the other methods at the moment.

**Expected behavior:**
Get the accessToken with all login methods and on every platform

**Steps to reproduce:**
Just use the plugin. Everyone in my team has the same behavior.

**Related code:**

export async function signInWithGoogle() {
    await FirebaseAuthentication.signInWithGoogle().then((result) => {
        console.log("result; ", result);
        console.log("accessToken: ", result.credential?.accessToken);
    });
}

**Capacitor doctor:**
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/ios: 3.4.3

[success] iOS looking great! 👌
[success] Android looking great! 👌

**Comment by jpsunb** [comment]
@robingenz, hi, love your work. But I can't get Google authentication to work on the server side for Firebase on Android and iOS, but works on web. The email login works on all platforms. On the app it looks like the user is authenticated but when requests that requires authentication are denied. Tried last version v0.2.2.

My test, see below, is to make a function call and return the UID from the request. So Firestore rules cannot be applied either since the users are not authenticated. I'm assuming the requests are missing the auth token as described on this bug report or is this a different problem? 

Firebase Function
`export const whoAmI = functions.https.onCall(async (data, context) => {
  return context.auth?.uid ?? "No UID"; // context.auth is null if request comes from iOS and Android on Google login.
});
`

**Comment by robingenz** [comment]
> @robingenz, hi, love your work. But I can't get Google authentication to work on the server side for Firebase on Android and iOS, but works on web. The email login works on all platforms. On the app it looks like the user is authenticated but when requests that requires authentication are denied. Tried last version v0.2.2.
> 
> My test, see below, is to make a function call and return the UID from the request. So Firestore rules cannot be applied either since the users are not authenticated. I'm assuming the requests are missing the auth token as described on this bug report or is this a different problem?
> 
> Firebase Function `export const whoAmI = functions.https.onCall(async (data, context) => { return context.auth?.uid ?? "No UID"; // context.auth is null if request comes from iOS and Android on Google login. }); `

That is another problem. I guess you sign in the user only on the native layer and not on the web layer (see [firebase-js-sdk.md](https://github.com/robingenz/capacitor-firebase/blob/main/packages/authentication/docs/firebase-js-sdk.md)). Please create a new issue if the problem persists

**Comment by jpsunb** [comment]
@robingenz, thanks! You were right. The problem was solved by adding `await signInWithCredential(auth, credential);`.

**Comment by LynearIngression** [comment]
I have a similar problem on iOS with Apple.

This is a problem because in order to pass apple review you have to have in-app account deletion and sign-in revoking.  To revoke an apple login you need either the accessToken or the refreshToken.

https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens

FirebaseAuthentication.signInWithApple()

On web I get this:
{
    "user": {
        ...
    },
    "credential": {
        "providerId": "apple.com",
        "accessToken": "afe...6g",
        "idToken": "eyJtrj...itU00_g"
    }
}
On an actual iPad I get this (no user because skipNativeAuth=true, but either way no accessTokens come back).
{
"credential": {
"nonce":".fkb...",
"providerId":"apple.com",
"idToken":"eyb..."
}
}

Using the credential to log in on the weblayer returns really long firebase tokens.  Apple accessTokens are pretty short.


The token that comes back on the web version is a valid apple token because I can successfully sign a JWT and revoke it on the apple end point.

I am on 0.3.1

Are they available somewhere else that I am missing?

**Comment by robingenz** [comment]
@lucasschulte There were several bug fixes in the past and the Firebase iOS SDK was also updated. Please test if the problem still exists in version 1.1.0 of the plugin.

@LynearIngression Unfortunately, the SDK does not give me access to the Apple Access Token but to the Authorization Code. With the authorization code it works, see [this SO answer](https://stackoverflow.com/a/72876563/6731412).
Here is a dev build (#213) that now returns the Authorization Code:

```
npm i @capacitor-firebase/authentication@1.1.0-dev.26640bb.1664634660
```

If it doesn't work or you have questions please create a new issue.

**Comment by LynearIngression** [comment]
Hi thank you for the fix.  

I am in the middle of updating to Capacitor4 and I broke everything.  I am updating to the newest authentication while I am at it.  I can exchange the authorization code for the tokens I need server-side.

I also need displayName which I believe apple only ever sends once, ever, per account (unless you revoke).  I think I see it added, so I will test it once I have finished resolving all the changes.
